---
# sample ansible-playbook script to install comma dependencies and build comma from source; include it as it is or copy to your playbook

- hosts: localhost
  connection: local
  vars:
  - build_j: 6
  - base: "{{ ansible_env.HOME }}"
  - src_dir: "{{ base }}/src/comma"
  - build_dir: "{{ base }}/build/comma"
  - cmake_options: "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DINSTALL_BASH_COMPLETION=ON -Dcomma_BUILD_XML=ON -Dcomma_BUILD_ZEROMQ=ON -Dcomma_INSTALL_WEB_SHELL=OFF"

  tasks:
  - name: "install comma dependencies"
    become: true
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
      - build-essential 
      - git
      - cmake-curses-gui
      - cmake
      - perl
      - python
      - libboost-all-dev
      - socat
      - libzmq3-dev
      - libgtest-dev
      - python-dev
      - python-numpy
      - libprocps-dev
      - recode
      
  - name: "comma: make source directory at {{ base }}"
    file: path={{ base }}/src state=directory
    file: path={{ base }}/build state=directory
    
  - name: "comma: clone"
    git:
        repo: "https://gitlab.com/orthographic/comma.git"
        dest: "{{ base }}/src/comma"
        clone: yes
        update: yes
        
  - name: "comma: make build directory at {{ base }}"
    file: dest="{{ build_dir }}" state=directory

  - name: "comma: cmake"
    shell: "/usr/bin/cmake {{ cmake_options }} {{ src_dir }} chdir={{ build_dir }}"

  - name: "comma: make"
    make:
        chdir: "{{ build_dir }}"
        params:
            MAKEFLAGS: "-j {{ build_j }}"

  - name: "comma: install"
    become: true
    make:
        chdir: "{{ build_dir }}"
        target: "install"
